name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11', '16' ]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2.1.5
      with:
        node-version: '12'
    - name: print Node version
      run: node --version
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
    - name: print Java version
      run: java -version
    - name: setup AWS CDK
      run: make setup
    - name: print CDK version
      run: cdk --version
    - uses: actions/cache@v2.1.4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build
      run: mvn --no-transfer-progress -B clean package
    - name: cdk synth
      run: cdk synth

  automerge:
    runs-on: [ubuntu-latest]
    name: automerge
    needs: [build]
    if: github.base_ref == 'main' && github.actor == 'dependabot[bot]'
    steps:
    - name: merge
      uses: actions/github-script@v3
      with:
        script: |
          github.pulls.merge({
            owner: context.payload.repository.owner.login,
            repo: context.payload.repository.name,
            pull_number: context.payload.pull_request.number,
            merge_method: 'squash'
          })
        github-token: ${{secrets.GITHUB_TOKEN}}
