name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: print Node version
      run: node --version
    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
        cache: 'maven'
    - name: print Java version
      run: java -version
    - name: setup AWS CDK
      run: make setup
    - name: print CDK version
      run: cdk --version
    - name: Build
      run: mvn --no-transfer-progress -B clean package
    - name: cdk synth
      run: cdk synth
